config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'responses/userlist'
  get 'assignments(/:id)/responselist', to:'assignments#responselist'
  get 'portfolios', to:'responses#userlist'
  get 'portfolios(/:user_id)', to:'responses#index'

  get 'like(/:response_id)', to: 'likes#like', as:"like_item"
  get 'unlike(/:response_id)', to: 'likes#unlike', as:"unlike_item"

  mount Ckeditor::Engine => '/ckeditor'
  resources :responses
  resources :presentations do
    collection do 
      get 'list'
    end
  end
  resources :assignments
  devise_for :views
  devise_for :users

  root 'assignments#index'
  get 'home/about'
  get 'home/assignments'

  post 'settings', to:'settings#save', as: 'save_settings' 
  get 'settings', to:'settings#show', as: 'show_settings' 

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	has_many :responses
	belongs_to :presentation
	validates :discussion_title, presence: true
	validates :due_date, presence: true


	def as_csv
	  CSV.generate do |csv|
	    csv << ["Student name","Response","Last updated"]
	    no_response = User.where.not(id: self.responses.pluck(:user_id)).where(admin: false)
	    self.responses.each do |response|
	      csv << [response.user.name, ActionController::Base.helpers.sanitize(response.content, :tags=>[]), response.updated_at]
	    end
	    no_response.each do |user|
	    	csv << [user.name, "(no response)", "-"]
	    end
	  end
	end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /assignments
  # GET /assignments.json
  def index
    @presentation = Presentation.current
    unless @presentation.nil?
      @assignments = Assignment.where(presentation_id: @presentation.id)
    end
    @assignment = Assignment.new

  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])
  end

  def responselist
      @assignment = Assignment.find(params[:id])
      if sort_column.nil?
        @response = Response.where(assignment_id: @assignment.id).order("user_name" + " " + "asc")
      else
        @response = Response.where(assignment_id: @assignment.id).order(sort_column + " " + sort_direction)
      end
      @no_response = User.where.not(id: @response.pluck(:user_id)).where(admin: false)
      respond_to do |format|
        format.html
        format.csv {send_data @assignment.as_csv, :filename=>@assignment.discussion_title+".csv"}
      end
  end

  # GET /assignments/new
  def new
    @presentation = Presentation.current
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
    @presentation = @assignment.presentation
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)
    @presentation = Presentation.current

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to :back, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to presentation_path(@assignment.presentation_id), notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def sort_column
    Response.where(assignment_id: @assignment.id).column_names.include?(params[:sort]) ? params[:sort] : "user_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end


    def assignment_params
      params.require(:assignment).permit(:discussion_title, :due_date, :discussion_question, :edit_question, :presentation_id, :slide_number)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<% if current_user.admin? %> 
<% if @presentation.nil? %>
<h2>You must upload the presentation first.</h2>
<% else %>

<%= form_for(@assignment) do |f| %>
                <% if @assignment.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

                    <ul>
                    <% @assignment.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                

                <div class="form-group">
                  <%= f.label :discussion_title, class:'control-label' %>
                  <%= f.text_field :discussion_title, class:'form-control'%>
                </div>

                <div class="form-group">
                  <%= f.label :discussion_question, class:'control-label' %>
                  <%= f.bootsy_area :discussion_question, class:'form-control', rows:8%>
                </div>

                <div class="form-group">
                  <%= f.label :slide_number, class:'control-label' %>
                  <%= f.number_field :slide_number, class:'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label :due_date, class:'control-label' %>
                  <%= f.datetime_select :due_date, class:'form-control' %>
                </div>

                
                  <%= f.hidden_field :presentation_id, value: @presentation.id %>
                


                <div class="form-group" id='controls'>
                  <%= f.submit "Save", class: 'btn btn-primary' %> 
                </div>

              <% end %>

<% end %>

<% else %> 
  <h1> Only Admins can view this page </h1> 
<% end %> 

app/views/assignments/edit.html.erb
<ol class='breadcrumb'>
	<li><%= link_to "Presentations", presentations_path %></li>
	<li><%= link_to @assignment.presentation.title, @assignment.presentation %></li>
	<li class='active'>Edit question</li>
</ol>
<div class='page-header'>
	<h1>Edit Question</h1>
</div>
<%= render 'form' %> <%= link_to 'Cancel', :back, class:'btn btn-link' %>

app/views/assignments/index.html.erb
<div class =" jumbotron" > 
  <h1>Welcome to <%= Setting.class_name %></h1>
  <div class='row'>
    <div class='col-md-<%= current_user.admin? ? 6 : 12 %>'>
      <p class='h2'><%= Setting.site_title %></p>
    </div>
    <% if current_user.admin? %>
      <div class='col-md-6 text-right'>

         <%= link_to 'New Presentation', new_presentation_path, class: 'btn btn-success visible-md-inline visible-lg-inline' %>
         <%= link_to 'New Presentation', new_presentation_path, class: 'btn btn-success btn-block visible-sm-block visible-xs-block' %>
        </div>
    <% end %>
  </div>
</div>



  <div class='page-header'>

    <% if !@presentation.nil? %>
      <h2 class='h1'>
        Current presentation: <%= @presentation.title %>
        <% if current_user.admin? %>
          <small><%= link_to 'Edit', edit_presentation_path(@presentation) %></small>
        <% end %>  

      </h2>
      <p>
        <%= link_to 'Download presentation', @presentation.slides.url, :download=>@presentation.title+".pdf", class:'btn btn-info' %>
        
      </p>
    <% else %>
      <h2 class='h1'>No presentations yet</h2>
    <% end %>
  </div>


  
  <%= render 'presentations/summary' %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/responselist.html.erb
<ol class='breadcrumb'>
    <li><%= link_to "Presentations", presentations_path %></li>
    <li><%= link_to @assignment.presentation.title, @assignment.presentation %></li>
    <li class='active'><%= @assignment.discussion_title %></li>
  </ol>
<div class='page-header'>
  <h1>Responses for Assignment: <%=@assignment.discussion_title%></h1>
  <% if current_user.admin? %>
    <p><%=link_to "Download all responses", {:controller => 'assignments', :action => 'responselist', :id => @assignment.id, :format=>:csv}, class: 'btn btn-primary'%></p>
  <% end %>
</div>
<table class='table'>
  <thead>
      <tr>
        <th><%= sortable "user_name", "Author", :id => @assignment.id %></th>
        <th><%= sortable "updated_at", "Last Updated", :id => @assignment.id%></th>
        <th>Response</th>
        <th colspan=2>Likes</th>
      </tr>
    </thead>
    <tbody>
      <% @response.each do |response| %>
        <tr data-response-id="<%= response.id %>">
          
          <td><%= response.user.name%></td>
          <td><%= time_ago_in_words(response.updated_at)%> ago</td>
          <td style='max-width: 500px'>
            <div class='response'>
              <%=  response.content.html_safe %>
            </div>
          </td>
          <td>
            <p class='btn-sm-padding-vertical like-count'>
              <%= pluralize response.likes.count, 'like' %> 
            </p>
          </td>
          <td> <% unless response.user.id == current_user.id %>
            <div class='no-js'>
              <%if Like.where(response_id: response.id, user_id: current_user.id).exists?%>
                <p><%= link_to 'Unlike', Like.where(response_id: response.id, user_id: current_user.id).first, method: :delete, class:'btn btn-sm btn-primary' %></p>
              <%else%>
                <%=form_for(Like.new) do |x|%>
                  <%=x.hidden_field :user_id, value: current_user.id%>
                  <%=x.hidden_field :response_id, value: response.id%>
                  <p><%=x.submit "Like", class:'btn btn-sm btn-primary'%></p>
                <%end%>
              <% end %>
            </div>
            <div class='js' style='display:none;'>
             
                <button class='btn btn-primary btn-sm like-button'>
                <%if Like.where(response_id: response.id, user_id: current_user.id).exists?%>
                  Unlike
                <%else%>
                 Like
                <% end %>
                </button>
              </div>
               <% end %>
          </td>
        </tr>
      <% end %>
      <% if current_user.admin? %>
        <% @no_response.each do |student| %>
        <tr class='danger'>
          <td><%= student.name %></td>
          <td class='text-center'>-</td>
          <td><i>No submission</i></td>
          <td colspan='2'></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
</table>

<script type='text/javascript'>
function updateLikeCount(button,newLikes){
  button.parents("tr").find(".like-count").html(newLikes);
}

$(function(){
  $('.response').readmore({
    collapsedHeight: 50,
  });
  $('.no-js').hide();
  $('.js').show();

  $('.like-button').click(function(e){
    e.preventDefault();
    var response_id=$(this).parents("tr").attr('data-response-id');
    var button = $(this);
    if($(this).html().trim()=="Like"){
      $.ajax({
        url:"<%= like_item_path %>",
        data:{"response_id":response_id},
        method:"GET",
        dataType:"JSON"
        }).done(function(data){
          updateLikeCount(button,data.response_likes_words);
          button.html("Unlike");
        });
    }
    else{
       $.ajax({
        url:"<%= unlike_item_path %>",
        data:{"response_id":response_id},
        method:"GET",
        dataType:"JSON"
        }).done(function(data){
          updateLikeCount(button,data.words);
          button.html("Like");
        });
    }
  });

  
});



</script>

app/views/assignments/show.html.erb
<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %> 

app/views/assignments/userlist.html.erb
<div class='page-header'>
	<h1>User Portfolios</h1>
</div>
<table class='table table-bordered'>
	<thead>
	    <tr>
	      <th>Name</th>
	      <th>Link to Portfolio</th>
	    </tr>
  	</thead>
  	<tbody>
	    <% @users.each do |user| %>
	      <tr>
	        <td><%= user.name %></td>
	        <td><%= link_to "Go",  {:controller => 'posts', :action => 'index', :user_id => user.id}%></td>
	      </tr>
	    <% end %>
  	</tbody>
</table>