config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'responses/userlist'
  get 'assignments(/:id)/responselist', to:'assignments#responselist'
  get 'portfolios', to:'responses#userlist'
  get 'portfolios(/:user_id)', to:'responses#index'

  get 'like(/:response_id)', to: 'likes#like', as:"like_item"
  get 'unlike(/:response_id)', to: 'likes#unlike', as:"unlike_item"

  mount Ckeditor::Engine => '/ckeditor'
  resources :responses
  resources :presentations do
    collection do 
      get 'list'
    end
  end
  resources :assignments
  devise_for :views
  devise_for :users

  root 'assignments#index'
  get 'home/about'
  get 'home/assignments'

  post 'settings', to:'settings#save', as: 'save_settings' 
  get 'settings', to:'settings#show', as: 'show_settings' 

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
	has_attached_file :slides
	has_many :assignments 
		
	validates_attachment_content_type :slides, :content_type => ['application/pdf', 'image/jpeg', 'application/vnd.openxmlformats-officedocument.presentationml.presentation']
	
	validates :slides, :title, :presence => true

	def self.current
		self.all.order("created_at desc").first || nil
	end																			
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all.order("created_at desc")
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    @assignments=Assignment.where(presentation_id: @presentation.id)
    @assignment=Assignment.new
  end

  def list 
    @presentations = Presentation.all
  end 

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to assignments_path, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:slides, :title)
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_discussion.html.erb
<div class="row">
  <div class="col-md-8">
      <% unless @presentation.nil? %>
      <table class="table middle">
        <thead>
          <tr>
            <th>Question</th>
            <th>Slide</th>
            <th>Due Date</th>
            <th class='text-center' colspan="<%= !current_user.admin? ? 2 : 4 %>"></th>
          </tr>
        </thead>

        <tbody>
          <% @assignments.each do |assignment| %>
            <tr>
              <td><%= assignment.discussion_title %></td>
              <td><%= assignment.slide_number %></td>
              <td><%= assignment.due_date.strftime("%-b %-d at %I:%M%p") %></td>
              <%if !current_user.admin?%>
              <% if assignment.due_date < Time.zone.now %>
              <td class='text-danger text-center'>Due date has passed</td>
                <%elsif Response.where(user_id: current_user.id, assignment_id: assignment.id).exists?%>
                  <%@response = Response.where(user_id: current_user.id, assignment_id: assignment.id).first%>
                  <td><%=link_to "Edit response", {:controller => 'responses', :action => 'edit', :id => @response.id, :assignment_id => assignment.id}, class: 'btn btn-warning btn-block'%></td>
                <%else%>
                  <td><%= link_to "Start assignment", {:controller => 'responses', :action => 'new', :assignment_id => assignment.id}, class: 'btn btn-success btn-block'%></td>
                <%end%>
              <%end%>
              <td><%=link_to "View class responses", {:controller => 'assignments', :action => 'responselist', :id => assignment.id}, class: 'btn btn-link'%></td>
              <%if current_user.admin?%>
                <td><%=link_to fa_icon("download"), {:controller => 'assignments', :action => 'responselist', :id => assignment.id, :format=>:csv},  title:"Download class responses", class: 'btn btn-primary btn-icon'%></td>
                <td><%= link_to fa_icon("pencil"),  {:controller => 'assignments', :action => 'edit', :id => assignment.id}, class: 'btn btn-primary btn-icon', title:'Edit question' %></td>
                <td><%= link_to fa_icon("trash"), assignment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-icon', title:'Delete question' %></td>
              <%end%>
            </tr>
          <% end %>
           <% if @assignments.empty? %>
            <td colspan='7' class='text-center'><i>No discussions yet</i></td>
          <% end %>
          <% if current_user.admin?%>
          <tr>
            <td colspan='7'>
              <p class='text-center'><a href='#' id='new_question'>New question...</a></p>
              <%= render 'assignments/form' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
  </div> 

  <% unless @presentation.nil? %>

  <div class="col-md-4"> 
      <iframe class='pretty-frame' id='presentation' src="<%= @presentation.slides.url %>" frameborder="0" width="100%" height="400" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
   </div>
   
  
  <% end %>
  </div>

 
<script type='text/javascript'>
$(function(){
  $('#new_assignment').hide();

  $('#controls').append("<a id='cancel_new_question' class='btn btn-link'>cancel</a>");


  $('#new_question').click(function(e){
    e.preventDefault();
    $(this).hide();
    $('#new_assignment').show();
  });
  $('#cancel_new_question').click(function(e){
    $('#new_question').show();
    $('#new_assignment').hide();
  });
});
</script>

app/views/presentations/_form.html.erb
<%= form_for @presentation, :html => {:multipart => true} do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% @presentation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :title, class:'control-label' %><br>
    <%= f.text_field :title, class:'form-control'%>
  </div>

       


     <% unless @presentation.slides.blank? %>

        <div class='form-group'>
          <label class='conrol-label'>Current slides</label>
            <iframe class='pretty-frame' id='presentation' src="<%= @presentation.slides.url %>" frameborder="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
        </div>

    <% end %>
    <div class="form-group">

        <%= f.label :slides, @presentation.slides.blank? ? "Slides" : "Change slides", class:'control-label' %><br>
        <%= f.file_field :slides, class:'form-control'%>
      </div>
  
  <div class="form-group">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/presentations/_summary.html.erb
<div class="row">
  <div class="col-md-8">
      <% unless @presentation.nil? %>
      <table class="table middle">
        <thead>
          <tr>
            <th>Question</th>
            <th>Slide</th>
            <th>Due Date</th>
            <th class='text-center' colspan="<%= !current_user.admin? ? 2 : 4 %>"></th>
          </tr>
        </thead>

        <tbody>
          <% @assignments.each do |assignment| %>
            <tr>
              <td><%= assignment.discussion_title %></td>
              <td><%= assignment.slide_number %></td>
              <td><%= assignment.due_date.strftime("%-b %-d at %I:%M%p") %></td>
              <%if !current_user.admin?%>
              <% if assignment.due_date < Time.zone.now %>
              <td class='text-danger text-center'>Due date has passed</td>
                <%elsif Response.where(user_id: current_user.id, assignment_id: assignment.id).exists?%>
                  <%@response = Response.where(user_id: current_user.id, assignment_id: assignment.id).first%>
                  <td><%=link_to "Edit response", {:controller => 'responses', :action => 'edit', :id => @response.id, :assignment_id => assignment.id}, class: 'btn btn-warning btn-block'%></td>
                <%else%>
                  <td><%= link_to "Start assignment", {:controller => 'responses', :action => 'new', :assignment_id => assignment.id}, class: 'btn btn-success btn-block'%></td>
                <%end%>
              <%end%>
              <td><%=link_to "View class responses", {:controller => 'assignments', :action => 'responselist', :id => assignment.id}, class: 'btn btn-link'%></td>
              <%if current_user.admin?%>
                <td><%=link_to fa_icon("download"), {:controller => 'assignments', :action => 'responselist', :id => assignment.id, :format=>:csv},  title:"Download class responses", class: 'btn btn-primary btn-icon'%></td>
                <td><%= link_to fa_icon("pencil"),  {:controller => 'assignments', :action => 'edit', :id => assignment.id}, class: 'btn btn-primary btn-icon', title:'Edit question' %></td>
                <td><%= link_to fa_icon("trash"), assignment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-icon', title:'Delete question' %></td>
              <%end%>
            </tr>
          <% end %>
           <% if @assignments.empty? %>
            <td colspan='7' class='text-center'><i>No discussions yet</i></td>
          <% end %>
          <% if current_user.admin?%>
          <tr>
            <td colspan='7'>
              <p class='text-center'><a href='#' id='new_question'>New question...</a></p>
              <%= render 'assignments/form' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
  </div> 

  <% unless @presentation.nil? %>

  <div class="col-md-4"> 
      <iframe class='pretty-frame' id='presentation' src="<%= @presentation.slides.url %>" frameborder="0" width="100%" height="400" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
   </div>
   
  
  <% end %>
  </div>

 
<script type='text/javascript'>
$(function(){
  $('#new_assignment').hide();

  $('#controls').append("<a id='cancel_new_question' class='btn btn-link'>cancel</a>");


  $('#new_question').click(function(e){
    e.preventDefault();
    $(this).hide();
    $('#new_assignment').show();
  });
  $('#cancel_new_question').click(function(e){
    $('#new_question').show();
    $('#new_assignment').hide();
  });
});
</script>

app/views/presentations/edit.html.erb
<ol class='breadcrumb'>
	<li><%= link_to "Presentations", presentations_path %></li>
	<li><%= link_to @presentation.title, @presentation %></li>
	<li class='active'>Edit</li>
</ol>
<div class='page-header'>
	<h1>Editing Presentation</h1>
</div>
<div class='row'>
	<div class='col-md-8'>
		<%= render 'form' %>
		<%= link_to 'Cancel', :back %>
	</div>
</div>

app/views/presentations/index.html.erb
<ol class='breadcrumb'>
	<li class='active'>Presentations</li>
</ol>
<div class='page-header'>
	<h1>Presentations</h1>
	
</div>




<div class='row'>
	<div class='col-md-12'>
	<% if current_user.admin %>
		<p><%= link_to 'New Presentation', new_presentation_path, class:'btn btn-success' %></p>
	<% end %>


	<table class='table middle'>
		<thead>
			<tr>
				<th>Title</th>
				<th>Link</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @presentations.each do |presentation| %>
			<tr>

				<td>
					<% if presentation == Presentation.current %>
						<b>
					<% end %>
					<%= presentation.title %>
					<% if presentation == Presentation.current %>
						 (current presentation) </b>
					<% end %>
				</td>
				<td> 
				<%= link_to 'View presentation and discussions', presentation_path(presentation), class: 'btn-padding-vertical' %>
				</td>
				<td>
				<% if current_user.admin %>
				<%= link_to fa_icon("pencil"), edit_presentation_path(presentation), class: 'btn btn-primary btn-icon', title:'Edit' %>
				<%= link_to fa_icon("trash"), presentation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-icon', title:'Delete' %>
				<% end %>
				</td>
			</tr>
			<% end %> 
		</tr>
	</tbody>
	</table>
	</div>
</div>

app/views/presentations/list.html.erb
<h1>All Responses to Discussion Questions : <%=@presentation%></h1>

<% @presentations.each do |presentation| %>

		<table class='table table-bordered'>
		  <thead>
		    
		  </thead>
		    <tbody>
		 		<% presentation.assignments.each do |assignment| %> 
		 		<tr>
		 			<h3><%=assignment.discussion_title%> </h3> <h5><%= assignment.due_date %></h5>
					<table class='table table-bordered'>
					  <thead>
					      <tr>
					        <th>Headline<%#= sortable "title", "Headline", :id => assignment.id %></th>
					        <th>Author<%#= sortable "user_name", "Author", :id => assignment.id %></th>
					        <th>Updated<%#= sortable "updated_at", "Last Updated", :id => assignment.id%></th>
					      </tr>
					    </thead>
					    <tbody>
					      <% assignment.responses.each do |response| %>
					        <tr>
					          <td><%= link_to response.content.html_safe, response %></td>
					          <td><%= response.user.name%></td>
					          <td><%= time_ago_in_words(response.updated_at)%> ago</td>
					        </tr>
					      <% end %>
					    </tbody>
					</table>
		 		</tr> 
		      <% end %>
		    </tbody>
		</table>
<% end %> 

app/views/presentations/new.html.erb
<ol class='breadcrumb'>
	<li><%= link_to "Presentations", presentations_path %></li>
	<li class='active'>New Presentation</li>
</ol>
<div class='page-header'>
	<h1>New Presentation</h1>
</div>
<%= render 'form' %>

<%= link_to 'Cancel', presentations_path %>

app/views/presentations/show.html.erb
<ol class='breadcrumb'>
	<li><%= link_to "Presentations", presentations_path %></li>
	<li class='active'><%= @presentation.title %></li>
</ol>
<div class='page-header'>

	<h1>
		<%= @presentation.title %>
		<% if current_user.admin? %>
			<small><%= link_to 'Edit', edit_presentation_path(@presentation) %></small>
		<% end %>
	</h1>
	 
	<p>
		
		<%= link_to 'Download presentation', @presentation.slides.url, :download=>@presentation.title+".pdf", class:'btn btn-info' %>

	</p>
</div>




<%= render 'summary' %>