config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'responses/userlist'
  get 'assignments(/:id)/responselist', to:'assignments#responselist'
  get 'portfolios', to:'responses#userlist'
  get 'portfolios(/:user_id)', to:'responses#index'

  get 'like(/:response_id)', to: 'likes#like', as:"like_item"
  get 'unlike(/:response_id)', to: 'likes#unlike', as:"unlike_item"

  mount Ckeditor::Engine => '/ckeditor'
  resources :responses
  resources :presentations do
    collection do 
      get 'list'
    end
  end
  resources :assignments
  devise_for :views
  devise_for :users

  root 'assignments#index'
  get 'home/about'
  get 'home/assignments'

  post 'settings', to:'settings#save', as: 'save_settings' 
  get 'settings', to:'settings#show', as: 'show_settings' 

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :response
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.where(user_id: current_user.id)
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  def like
    @like = Like.new(user_id: current_user.id, response_id: params[:response_id])
    respond_to do |format|
      if @like.save
        format.json {render :show}
      end
    end
  end

  def unlike
    @like = Like.where(user_id: current_user.id, response_id: params[:response_id]).first
    respond_to do |format|
      if @like.destroy
        @likes = Like.where(response_id: params[:response_id])
        format.json {render json: {"number"=>@likes.size, "words"=>view_context.pluralize(@likes.size, "like")}}
      end
    end
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to :back }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like.response, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:user_id, :response_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<ol class='breadcrumb'>
  <li class='active'>Likes</li>
</ol>
<div class='page-header'>
  <h1>My likes</h1>
</div>



<% if !@likes.empty? %>
  <table class='table'>
    <thead>
      <tr>
        <th>Assignment</th>
        <th>Author</th>
        <th>Content</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @likes.each do |like| %>
        <tr>
          <td><%= like.response.assignment.discussion_title %></td>
          <td><%= like.response.user.name %></td>
          <td style='max-width: 650px;'><div class='response'><%= like.response.content.html_safe %></div></td>
          <td><p><%= link_to 'Unlike', like, method: :delete, class:'btn btn-primary btn-sm' %></p> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<p><i>You have not liked any posts yet</i></p>
<% end %>

<script type='text/javascript'>
$(function(){
  $('.response').readmore({
    collapsedHeight: 50,
  });
});
</script>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>