config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'responses/userlist'
  get 'assignments(/:id)/responselist', to:'assignments#responselist'
  get 'portfolios', to:'responses#userlist'
  get 'portfolios(/:user_id)', to:'responses#index'

  get 'like(/:response_id)', to: 'likes#like', as:"like_item"
  get 'unlike(/:response_id)', to: 'likes#unlike', as:"unlike_item"

  mount Ckeditor::Engine => '/ckeditor'
  resources :responses
  resources :presentations do
    collection do 
      get 'list'
    end
  end
  resources :assignments
  devise_for :views
  devise_for :users

  root 'assignments#index'
  get 'home/about'
  get 'home/assignments'

  post 'settings', to:'settings#save', as: 'save_settings' 
  get 'settings', to:'settings#show', as: 'show_settings' 

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def assignments
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to Setting.site_title, root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        	<% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li > <%= link_to 'Home', root_path  %> </li >
			<li > <%= link_to 'Presentations', presentations_path  %> </li >
      
			<% if current_user.admin? %>
				<li> <%= link_to 'Portfolios', portfolios_path %> </li >
        <%if Setting.show_settings_page %>
				  <li> <%= link_to 'Site Settings', show_settings_path %> </li >
        <% end %>
			<% end %>
      <li> <%= link_to 'About This Class', home_about_path %> </li >
      <li > <%= link_to 'My likes', likes_path %></li >

            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
            <li > <%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li >
          </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/home/about.html.erb
<ol class='breadcrumb'>
	<li class='active'>About</li>
</ol>
<div class='page-header'>
	<h1> About This Class </h1>
</div>
<%= Setting.about_text.html_safe %>

app/views/home/index.html.erb
<div class =" jumbotron" > 
  <h1>Welcome to <%= Setting.class_name %></h1> 
  <p class='h2'><%= Setting.site_title %></p>
</div>

<iframe class='pretty-frame' src="http://localhost:3000/presentations" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>